In [7]:
words = ['apple', 'orange', 'pear', 'milk', 'otter', 'snake','iguana','tiger','eagle']
for word in words:
    if word[0] in 'aeiou':
        print(word)

apple
orange
otter
iguana
eagle


In [9]:
words_starting_with_vowel = [word for word in words if word[0] in 'aeiou']
print (words_starting_with_vowel)


['apple', 'orange', 'otter', 'iguana', 'eagle']


In [15]:
import ast,sys
input_str = sys.stdin.read()
input_list = ['wood', 'old', 'apple', 'big', 'item', 'euphoria'] 
vowels = ['a','e','i','o','u']
list_vowel = [word for word in input_list if word[0].lower() in vowels]

print(list_vowel)

['old', 'apple', 'item', 'euphoria']


In [3]:
import numpy as np

A = np.array ([[1,2,3,4], [5,6,7,8], [2,3,4,5], [1,1,1,1]])

print (A)
print (A.T)

print (np.dot(A, A.T))

[[1 2 3 4]
 [5 6 7 8]
 [2 3 4 5]
 [1 1 1 1]]
[[1 5 2 1]
 [2 6 3 1]
 [3 7 4 1]
 [4 8 5 1]]
[[ 30  70  40  10]
 [ 70 174  96  26]
 [ 40  96  54  14]
 [ 10  26  14   4]]


In [5]:
import numpy as np

A = np.array([[2, 6, -1], 
              [1, 2, -2], 
              [-5, 0, 2]])
b = np.array([0, 1, 8])

# compute the inverse
A_inv = np.linalg.inv(A)

# solution: A_inv * b
x = np.dot(A_inv, b)
print(x) # returns [ 0.  0. -1.]

[-2.   0.5 -1. ]


In [6]:
import numpy as np

A = np.array ([[0,-1], [1, 0]])

print (np.linalg.inv(A))

[[ 0.  1.]
 [-1. -0.]]


In [12]:
import numpy as np

A = np.array ([[2, -1, -1], 
              [2, -1, 1], 
              [4, -2, -3]])

print ( np.linalg.matrix_rank(A))

2


In [11]:
import numpy as np

A = np.array([[2, -1, -1], 
              [2, -1, 1], 
              [4, -2, -3]])

b = np.array([1, 0, -1])

print (np.linalg.det(A))


0.0


In [17]:
import numpy as np

A = np.array ([[4,7], [9,6]])
print (np.linalg.eig(A))


(array([-3., 13.]), array([[-0.70710678, -0.61394061],
       [ 0.70710678, -0.78935222]]))
